### ISSUE TITLE
Actividad MySQL Departamentos

### ISSUE THREAD

**Issue by oscarcillo** [oscarcillo/AccesoDatos#8]
Primer commit 5ec2b10a5db87d98752a0e3117a0715a8972f6a4
Segundo commit fb7483f37a5b5859b1c3543fcddef0ed3e9bd67f

Enlace a los fichero 
[ConexionBD](https://github.com/oscarcillo/AccesoDatos/blob/5ec2b10a5db87d98752a0e3117a0715a8972f6a4/src/UD02_P01_Conectores_MySQL/A01_ConexionBD.java)
[Departamento](https://github.com/oscarcillo/AccesoDatos/blob/fb7483f37a5b5859b1c3543fcddef0ed3e9bd67f/src/UD02_P01_Conectores_MySQL/A01_Departamento.java)

**Comment by franlu** [comment]
Muy bien y con los métodos comentados :+1: :ok_hand:
